# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roadrunner < Formula
  desc "Beeper Desktop CLI for chats, messages, search, reminders."
  homepage "https://github.com/johntheyoung/roadrunner"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/johntheyoung/roadrunner/releases/download/v0.6.0/roadrunner_0.6.0_darwin_amd64.tar.gz"
      sha256 "a87fccba306ef6bdc22023a29c18e5c1943883c8f006f277d158339f1d3efe07"

      def install
        bin.install "rr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/johntheyoung/roadrunner/releases/download/v0.6.0/roadrunner_0.6.0_darwin_arm64.tar.gz"
      sha256 "30cd5ffdfda2aa5909938e073c2808396cb149c98a368dd5d80d7541ac071975"

      def install
        bin.install "rr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/johntheyoung/roadrunner/releases/download/v0.6.0/roadrunner_0.6.0_linux_amd64.tar.gz"
      sha256 "10ea354ffe4f97384fb5956568a9f2488ad8886fa25d8de6f3df682769d3365f"
      def install
        bin.install "rr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/johntheyoung/roadrunner/releases/download/v0.6.0/roadrunner_0.6.0_linux_arm64.tar.gz"
      sha256 "94f82c67381792d1ae4a19f55f2635d77c58f8e4520f8a0e5f61fb2942b6ebce"
      def install
        bin.install "rr"
      end
    end
  end

  test do
    system "#{bin}/rr", "version"
  end
end
