# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roadrunner < Formula
  desc "Beeper Desktop CLI for chats, messages, search, reminders."
  homepage "https://github.com/johntheyoung/roadrunner"
  version "0.14.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/johntheyoung/roadrunner/releases/download/v0.14.3/roadrunner_0.14.3_darwin_amd64.tar.gz"
      sha256 "1a79f15636466ccb88080b15d9ccef53e5555f3c636bf699ef0f6f55e2b639b1"

      def install
        bin.install "rr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/johntheyoung/roadrunner/releases/download/v0.14.3/roadrunner_0.14.3_darwin_arm64.tar.gz"
      sha256 "35f275abd0ee9fc29e5a86c9350db2d459d269bf00c530194b18607441c84418"

      def install
        bin.install "rr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/johntheyoung/roadrunner/releases/download/v0.14.3/roadrunner_0.14.3_linux_amd64.tar.gz"
      sha256 "609824a29f84a1e4a17a7b68c11b4aa57aedc64109f5c0187fa50506a88dd664"
      def install
        bin.install "rr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/johntheyoung/roadrunner/releases/download/v0.14.3/roadrunner_0.14.3_linux_arm64.tar.gz"
      sha256 "dce1fd52b0c5d8926d236733b24df570e54ae620411362ca8e6a9b9ef2355f57"
      def install
        bin.install "rr"
      end
    end
  end

  test do
    system "#{bin}/rr", "version"
  end
end
